// <auto-generated />
namespace CarryMultipleAppliesDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddTable_M_UserAndAddColumn_UserNameByT_ApplyUsersAndT_ApplyHistories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTable_M_UserAndAddColumn_UserNameByT_ApplyUsersAndT_ApplyHistories));
        
        string IMigrationMetadata.Id
        {
            get { return "202006072320404_AddTable_M_UserAndAddColumn_UserNameByT_ApplyUsersAndT_ApplyHistories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
