// <auto-generated />
namespace CarryMultipleAppliesDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DropTale_T_ApplyUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropTale_T_ApplyUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "202006072339435_DropTale_T_ApplyUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
