// <auto-generated />
namespace CarryMultipleAppliesDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DropT_ApplyAndT_Histories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropT_ApplyAndT_Histories));
        
        string IMigrationMetadata.Id
        {
            get { return "202006131212173_DropT_ApplyAndT_Histories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
