// <auto-generated />
namespace CarryMultipleAppliesDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DropTableAgain_T_ApplyUsersType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropTableAgain_T_ApplyUsersType));
        
        string IMigrationMetadata.Id
        {
            get { return "202006072352153_DropTableAgain_T_ApplyUsersType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
